name: Build EXE

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyinstaller pywin32 openpyxl

      - name: Build EXE
        run: pyinstaller --onefile outlook_to_excel.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: outlook_to_excel
          path: dist/outlook_to_excel.exe
